In [1]:
import pandas as pd

from config.project_config import get_data_path

## Romeo
- sigma: 0.2 & 0.3

In [2]:
sub_directory = "2025_10_16_Romeo"
utilizations = [0.75, 0.85, 0.95]

all_experiments = []
all_schedules = []

for u in utilizations:
    experiments_file_path = get_data_path(
        sub_directory,
        f"experiments_{u:.2f}".replace(".", "_")
    )
    schedules_file_path = get_data_path(
        sub_directory,
        f"schedules_{u:.2f}".replace(".", "_")
    )

    # Laden, wenn Datei existiert
    try:
        df_exp = pd.read_csv(f"{experiments_file_path}.csv")
        df_sch = pd.read_csv(f"{schedules_file_path}.csv")

        # optional: Spalte zur Kennzeichnung hinzufügen
        df_exp["max_utilization"] = u
        df_sch["max_utilization"] = u

        all_experiments.append(df_exp)
        all_schedules.append(df_sch)
    except FileNotFoundError:
        print(f"⚠️ Dateien für Utilization {u:.2f} nicht gefunden – übersprungen.")

# Alles zusammenführen
df_experiments = pd.concat(all_experiments, ignore_index=True)
df_schedules = pd.concat(all_schedules, ignore_index=True)

print(f"Geladen: {len(df_experiments)} Experimentzeilen, {len(df_schedules)} Schedulezeilen")

Geladen: 129 Experimentzeilen, 728579 Schedulezeilen

In [3]:
# IDs, die entfernt werden sollen (81 bis inkl. 89)
ids_to_remove = list(range(81, 90))  # 90 ist exklusiv

In [4]:
df_experiments = df_experiments.sort_values(by="Experiment_ID").reset_index(drop=True)
df_experiments_romeo = df_experiments[~df_experiments["Experiment_ID"].isin(ids_to_remove)].reset_index(drop=True)
df_experiments_romeo["Experiment_ID"] = "R-" + df_experiments_romeo["Experiment_ID"].astype(str)
df_experiments_romeo

,Experiment_ID,Abs Lateness Ratio,Inner Tardiness Ratio,Max Bottleneck Utilization,Sim Sigma,Shift Length,w_t,w_e,w_dev,Experiment_Type,max_utilization
0,R-1,0.25,1.00,0.75,0.2,1440,1,0,3,CP,0.75
1,R-2,0.25,0.75,0.75,0.2,1440,3,1,12,CP,0.75
2,R-3,0.25,0.50,0.75,0.2,1440,1,1,6,CP,0.75
3,R-4,0.25,0.25,0.75,0.2,1440,1,3,12,CP,0.75
4,R-5,0.25,0.00,0.75,0.2,1440,0,1,3,CP,0.75
...,...,...,...,...,...,...,...,...,...,...,...
115,R-125,1.00,1.00,0.95,0.3,1440,1,0,0,CP,0.95
116,R-126,1.00,0.75,0.95,0.3,1440,3,1,0,CP,0.95
117,R-127,1.00,0.50,0.95,0.3,1440,1,1,0,CP,0.95
118,R-128,1.00,0.25,0.95,0.3,1440,1,3,0,CP,0.95
119,R-129,1.00,0.00,0.95,0.3,1440,0,1,0,CP,0.95

In [5]:
df_schedules_romeo = df_schedules[~df_schedules["Experiment_ID"].isin(ids_to_remove)].reset_index(drop=True)
df_schedules_romeo["Experiment_ID"]   = "R-" + df_schedules_romeo["Experiment_ID"].astype(str)
df_schedules_romeo

,Job,Routing_ID,Experiment_ID,Arrival,Ready Time,Due Date,Shift,Operation,Machine,Original Duration,Start,End,max_utilization
0,01-07500-0000,01-07,R-1,0,1440,3405,1,0,M02,31,2150,2181,0.75
1,01-07500-0000,01-07,R-2,0,1440,3405,1,0,M02,31,2133,2164,0.75
2,01-07500-0000,01-07,R-3,0,1440,3405,1,0,M02,31,1762,1793,0.75
3,01-07500-0000,01-07,R-4,0,1440,3405,1,0,M02,31,2133,2164,0.75
4,01-07500-0000,01-07,R-5,0,1440,3405,1,0,M02,31,1810,1841,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
686206,01-09500-0460,01-03,R-125,31544,31680,34164,22,9,M05,43,33513,33556,0.95
686207,01-09500-0460,01-03,R-126,31544,31680,34164,22,9,M05,43,34121,34164,0.95
686208,01-09500-0460,01-03,R-127,31544,31680,34164,22,9,M05,43,34121,34164,0.95
686209,01-09500-0460,01-03,R-128,31544,31680,34164,22,9,M05,43,34121,34164,0.95
686210,01-09500-0460,01-03,R-129,31544,31680,34164,22,9,M05,43,34121,34164,0.95

## Bernard

In [6]:
sub_directory = "2025_10_16_Bernard"
utilizations = [0.75, 0.85, 0.95]

all_experiments = []
all_schedules = []

df_experiments = None
df_schedules = None

for u in utilizations:
    experiments_file_path = get_data_path(
        sub_directory,
        f"experiments_{u:.2f}".replace(".", "_")
    )
    schedules_file_path = get_data_path(
        sub_directory,
        f"schedules_{u:.2f}".replace(".", "_")
    )

    # Laden, wenn Datei existiert
    try:
        df_exp = pd.read_csv(f"{experiments_file_path}.csv")
        df_sch = pd.read_csv(f"{schedules_file_path}.csv")

        # optional: Spalte zur Kennzeichnung hinzufügen
        df_exp["max_utilization"] = u
        df_sch["max_utilization"] = u

        all_experiments.append(df_exp)
        all_schedules.append(df_sch)
    except FileNotFoundError:
        print(f"⚠️ Dateien für Utilization {u:.2f} nicht gefunden – übersprungen.")

# Alles zusammenführen
df_experiments = pd.concat(all_experiments, ignore_index=True)
df_schedules = pd.concat(all_schedules, ignore_index=True)

print(f"Geladen: {len(df_experiments)} Experimentzeilen, {len(df_schedules)} Schedulezeilen")

Geladen: 60 Experimentzeilen, 328191 Schedulezeilen

In [7]:
df_experiments_bernard = df_experiments.sort_values(by="Experiment_ID").reset_index(drop=True)
df_experiments_bernard["Experiment_ID"] = "B-" + df_experiments_bernard["Experiment_ID"].astype(str)
df_experiments_bernard

,Experiment_ID,Abs Lateness Ratio,Inner Tardiness Ratio,Max Bottleneck Utilization,Sim Sigma,Shift Length,w_t,w_e,w_dev,Experiment_Type,max_utilization
0,B-1,0.25,1.00,0.75,0.1,1440,1,0,3,CP,0.75
1,B-2,0.25,0.75,0.75,0.1,1440,3,1,12,CP,0.75
2,B-3,0.25,0.50,0.75,0.1,1440,1,1,6,CP,0.75
3,B-4,0.25,0.25,0.75,0.1,1440,1,3,12,CP,0.75
4,B-5,0.25,0.00,0.75,0.1,1440,0,1,3,CP,0.75
5,B-6,0.50,1.00,0.75,0.1,1440,1,0,1,CP,0.75
6,B-7,0.50,0.75,0.75,0.1,1440,3,1,4,CP,0.75
7,B-8,0.50,0.50,0.75,0.1,1440,1,1,2,CP,0.75
8,B-9,0.50,0.25,0.75,0.1,1440,1,3,4,CP,0.75
9,B-10,0.50,0.00,0.75,0.1,1440,0,1,1,CP,0.75
10,B-11,0.75,1.00,0.75,0.1,1440,3,0,1,CP,0.75
11,B-12,0.75,0.75,0.75,0.1,1440,9,3,4,CP,0.75
12,B-13,0.75,0.50,0.75,0.1,1440,3,3,2,CP,0.75
13,B-14,0.75,0.25,0.75,0.1,1440,3,9,4,CP,0.75
14,B-15,0.75,0.00,0.75,0.1,1440,0,3,1,CP,0.75
15,B-16,1.00,1.00,0.75,0.1,1440,1,0,0,CP,0.75
16,B-17,1.00,0.75,0.75,0.1,1440,3,1,0,CP,0.75
17,B-18,1.00,0.50,0.75,0.1,1440,1,1,0,CP,0.75
18,B-19,1.00,0.25,0.75,0.1,1440,1,3,0,CP,0.75
19,B-20,1.00,0.00,0.75,0.1,1440,0,1,0,CP,0.75
20,B-21,0.25,1.00,0.85,0.1,1440,1,0,3,CP,0.85
21,B-22,0.25,0.75,0.85,0.1,1440,3,1,12,CP,0.85
22,B-23,0.25,0.50,0.85,0.1,1440,1,1,6,CP,0.85
23,B-24,0.25,0.25,0.85,0.1,1440,1,3,12,CP,0.85
24,B-25,0.25,0.00,0.85,0.1,1440,0,1,3,CP,0.85
25,B-26,0.50,1.00,0.85,0.1,1440,1,0,1,CP,0.85
26,B-27,0.50,0.75,0.85,0.1,1440,3,1,4,CP,0.85
27,B-28,0.50,0.50,0.85,0.1,1440,1,1,2,CP,0.85
28,B-29,0.50,0.25,0.85,0.1,1440,1,3,4,CP,0.85
29,B-30,0.50,0.00,0.85,0.1,1440,0,1,1,CP,0.85
30,B-31,0.75,1.00,0.85,0.1,1440,3,0,1,CP,0.85
31,B-32,0.75,0.75,0.85,0.1,1440,9,3,4,CP,0.85
32,B-33,0.75,0.50,0.85,0.1,1440,3,3,2,CP,0.85
33,B-34,0.75,0.25,0.85,0.1,1440,3,9,4,CP,0.85
34,B-35,0.75,0.00,0.85,0.1,1440,0,3,1,CP,0.85
35,B-36,1.00,1.00,0.85,0.1,1440,1,0,0,CP,0.85
36,B-37,1.00,0.75,0.85,0.1,1440,3,1,0,CP,0.85
37,B-38,1.00,0.50,0.85,0.1,1440,1,1,0,CP,0.85
38,B-39,1.00,0.25,0.85,0.1,1440,1,3,0,CP,0.85
39,B-40,1.00,0.00,0.85,0.1,1440,0,1,0,CP,0.85
40,B-41,0.25,1.00,0.95,0.1,1440,1,0,3,CP,0.95
41,B-42,0.25,0.75,0.95,0.1,1440,3,1,12,CP,0.95
42,B-43,0.25,0.50,0.95,0.1,1440,1,1,6,CP,0.95
43,B-44,0.25,0.25,0.95,0.1,1440,1,3,12,CP,0.95
44,B-45,0.25,0.00,0.95,0.1,1440,0,1,3,CP,0.95
45,B-46,0.50,1.00,0.95,0.1,1440,1,0,1,CP,0.95
46,B-47,0.50,0.75,0.95,0.1,1440,3,1,4,CP,0.95
47,B-48,0.50,0.50,0.95,0.1,1440,1,1,2,CP,0.95
48,B-49,0.50,0.25,0.95,0.1,1440,1,3,4,CP,0.95
49,B-50,0.50,0.00,0.95,0.1,1440,0,1,1,CP,0.95
50,B-51,0.75,1.00,0.95,0.1,1440,3,0,1,CP,0.95
51,B-52,0.75,0.75,0.95,0.1,1440,9,3,4,CP,0.95
52,B-53,0.75,0.50,0.95,0.1,1440,3,3,2,CP,0.95
53,B-54,0.75,0.25,0.95,0.1,1440,3,9,4,CP,0.95
54,B-55,0.75,0.00,0.95,0.1,1440,0,3,1,CP,0.95
55,B-56,1.00,1.00,0.95,0.1,1440,1,0,0,CP,0.95
56,B-57,1.00,0.75,0.95,0.1,1440,3,1,0,CP,0.95
57,B-58,1.00,0.50,0.95,0.1,1440,1,1,0,CP,0.95
58,B-59,1.00,0.25,0.95,0.1,1440,1,3,0,CP,0.95
59,B-60,1.00,0.00,0.95,0.1,1440,0,1,0,CP,0.95

In [8]:
df_schedules_bernard = df_schedules
df_schedules_bernard["Experiment_ID"]   = "B-" + df_schedules_bernard["Experiment_ID"].astype(str)
df_schedules_bernard

,Job,Routing_ID,Experiment_ID,Arrival,Ready Time,Due Date,Shift,Operation,Machine,Original Duration,Start,End,max_utilization
0,01-07500-0000,01-07,B-1,0,1440,3405,1,0,M02,31,2130,2161,0.75
1,01-07500-0000,01-07,B-2,0,1440,3405,1,0,M02,31,2133,2164,0.75
2,01-07500-0000,01-07,B-3,0,1440,3405,1,0,M02,31,1762,1793,0.75
3,01-07500-0000,01-07,B-4,0,1440,3405,1,0,M02,31,2150,2181,0.75
4,01-07500-0000,01-07,B-5,0,1440,3405,1,0,M02,31,1810,1841,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
328186,01-09500-0460,01-03,B-56,31544,31680,34164,22,9,M05,43,33427,33470,0.95
328187,01-09500-0460,01-03,B-57,31544,31680,34164,22,9,M05,43,34121,34164,0.95
328188,01-09500-0460,01-03,B-58,31544,31680,34164,22,9,M05,43,34121,34164,0.95
328189,01-09500-0460,01-03,B-59,31544,31680,34164,22,9,M05,43,34121,34164,0.95
328190,01-09500-0460,01-03,B-60,31544,31680,34164,22,9,M05,43,34121,34164,0.95

### Concat Romeo & Bernard

In [10]:
df_experiments_all = pd.concat([df_experiments_bernard, df_experiments_romeo], ignore_index=True)
df_experiments_all

,Experiment_ID,Abs Lateness Ratio,Inner Tardiness Ratio,Max Bottleneck Utilization,Sim Sigma,Shift Length,w_t,w_e,w_dev,Experiment_Type,max_utilization
0,B-1,0.25,1.00,0.75,0.1,1440,1,0,3,CP,0.75
1,B-2,0.25,0.75,0.75,0.1,1440,3,1,12,CP,0.75
2,B-3,0.25,0.50,0.75,0.1,1440,1,1,6,CP,0.75
3,B-4,0.25,0.25,0.75,0.1,1440,1,3,12,CP,0.75
4,B-5,0.25,0.00,0.75,0.1,1440,0,1,3,CP,0.75
...,...,...,...,...,...,...,...,...,...,...,...
175,R-125,1.00,1.00,0.95,0.3,1440,1,0,0,CP,0.95
176,R-126,1.00,0.75,0.95,0.3,1440,3,1,0,CP,0.95
177,R-127,1.00,0.50,0.95,0.3,1440,1,1,0,CP,0.95
178,R-128,1.00,0.25,0.95,0.3,1440,1,3,0,CP,0.95
179,R-129,1.00,0.00,0.95,0.3,1440,0,1,0,CP,0.95

In [12]:
df_experiments_all.to_csv("experiments_v01.csv", index=False)

In [11]:
df_schedules_all = pd.concat([df_schedules_bernard, df_schedules_romeo], ignore_index=True)
df_schedules_all

,Job,Routing_ID,Experiment_ID,Arrival,Ready Time,Due Date,Shift,Operation,Machine,Original Duration,Start,End,max_utilization
0,01-07500-0000,01-07,B-1,0,1440,3405,1,0,M02,31,2130,2161,0.75
1,01-07500-0000,01-07,B-2,0,1440,3405,1,0,M02,31,2133,2164,0.75
2,01-07500-0000,01-07,B-3,0,1440,3405,1,0,M02,31,1762,1793,0.75
3,01-07500-0000,01-07,B-4,0,1440,3405,1,0,M02,31,2150,2181,0.75
4,01-07500-0000,01-07,B-5,0,1440,3405,1,0,M02,31,1810,1841,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014397,01-09500-0460,01-03,R-125,31544,31680,34164,22,9,M05,43,33513,33556,0.95
1014398,01-09500-0460,01-03,R-126,31544,31680,34164,22,9,M05,43,34121,34164,0.95
1014399,01-09500-0460,01-03,R-127,31544,31680,34164,22,9,M05,43,34121,34164,0.95
1014400,01-09500-0460,01-03,R-128,31544,31680,34164,22,9,M05,43,34121,34164,0.95
1014401,01-09500-0460,01-03,R-129,31544,31680,34164,22,9,M05,43,34121,34164,0.95

In [13]:
df_schedules_all.to_csv("schedules_v01.csv", index=False)